# Generated by Django 3.0.3 on 2020-02-14 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BelongsTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AC', 'Accepted'), ('DE', 'Declined'), ('TE', 'Tentative'), ('WR', 'Waiting Response')], default='WR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('calendars', models.ManyToManyField(through='mycalendar.BelongsTo', to='mycalendar.Calendar')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycalendar.User')),
            ],
        ),
        migrations.AddField(
            model_name='calendar',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycalendar.User'),
        ),
        migrations.AddField(
            model_name='belongsto',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycalendar.Calendar'),
        ),
        migrations.AddField(
            model_name='belongsto',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycalendar.Event'),
        ),
    ]
