# Generated by Django 3.1.1 on 2020-09-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0003_event_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendar',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='event',
            name='calendars',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='BelongsTo',
        ),
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
