# Generated by Django 3.1.1 on 2020-09-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0004_auto_20200918_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(default='Acme', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='Finance', max_length=50),
            preserve_default=False,
        ),
    ]
