# Generated by Django 3.0.3 on 2020-02-14 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='calendar_title',
            new_name='title',
        ),
    ]
